services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollamadata:/root/.ollama
    networks: [ appnet ]
    healthcheck:
      test: ["CMD", "sh", "-c", "ollama list >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: app/api/Dockerfile
    container_name: stock-api
    env_file:
      - .env
    environment:
      - OLLAMA_BASE=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3}
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
      - ./cache:/app/.cache
      - hfmodels:/root/.cache/huggingface
    networks: [ appnet ]
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8000/healthz" ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  ui:
    build:
      context: .
      dockerfile: app/ui/Dockerfile
    container_name: stock-ui
    environment:
      - API_URL=http://api:8000
    depends_on:
      api:
        condition: service_started
    ports:
      - "8501:8501"
    networks: [ appnet ]
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  appnet:
    driver: bridge

volumes:
  hfmodels:
  ollamadata:
