services:
  api:
    build:
      context: .
      dockerfile: app/api/Dockerfile
    container_name: stock-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
      - hfmodels:/root/.cache/huggingface
    networks: [appnet]
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8000/healthz" ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  ui:
    build:
      context: .
      dockerfile: app/ui/Dockerfile
    container_name: stock-ui
    environment:
      - API_URL=http://api:8000
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8501:8501"
    networks: [appnet]
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  appnet:
    driver: bridge

volumes:
  hfmodels: