services:
  api:
    build:
      context: .
      dockerfile: app/api/Dockerfile
    container_name: stock-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - hfmodels:/root/.cache/huggingface
    networks: [appnet]
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8000/healthz" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 15s
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: app/ui/Dockerfile
    container_name: stock-ui
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8501:8501"
    networks: [appnet]
    restart: unless-stopped

networks:
  appnet:
    driver: bridge

volumes:
  hfmodels: