sonar.projectKey=vitoco84_ml-stock-sent
sonar.organization=vitoco84

sonar.sources=src
sonar.tests=tests

# Exclude non-source files from coverage
sonar.coverage.exclusions=tests/**,config/**,notebooks/**,**/__init__.py

# Coverage and Test Reports
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest-report.xml

# Ignore some rules (scoped better)
sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5,e6,e7
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S117
sonar.issue.ignore.multicriteria.e1.resourceKey=**
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S116
sonar.issue.ignore.multicriteria.e2.resourceKey=**
sonar.issue.ignore.multicriteria.e3.ruleKey=python:S7504
sonar.issue.ignore.multicriteria.e3.resourceKey=**
sonar.issue.ignore.multicriteria.e4.ruleKey=python:S100
sonar.issue.ignore.multicriteria.e4.resourceKey=**
sonar.issue.ignore.multicriteria.e5.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.e5.resourceKey=**
sonar.issue.ignore.multicriteria.e6.ruleKey=python:S1172
sonar.issue.ignore.multicriteria.e6.resourceKey=**
sonar.issue.ignore.multicriteria.e7.ruleKey=python:S107
sonar.issue.ignore.multicriteria.e7.resourceKey=**