env: dev

general:
  name: "ml-stock-sent"
  created: "2025-08-10"

data:
  fig_dir: "../data/figures"
  processed_dir: "../data/processed"
  raw_dir: "../data/raw"
  models_dir: "../data/models"
  reports_dir: "../data/reports"
  optuna_dir: "../data/optuna"

runtime:
  seed: 42
  horizon: 20
  horizon_list: [ 1, 5, 20 ]
  lag_horizon: 7
  n_trials: [ 30, 100 ]
  n_splits: 3
  n_jobs: 8
  gap: 20
  device: "cuda"
  subsample_train: 2000
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  days_history: 90
  max_sentiment_embeddings: 17
  target_mode: "rolling" # step or rolling