env: dev

general:
  name: "ml-stock-sent"
  created: "2025-08-10"

data:
  fig_dir: "../data/figures"
  processed_dir: "../data/processed"
  raw_dir: "../data/raw"
  models_dir: "../data/models"
  reports_dir: "../data/reports"

runtime:
  seed: 42
  horizon: 30
