[server]
headless = true
enableCORS = true
enableXsrfProtection = true
address = "0.0.0.0"
port = 8501
enableStaticServing = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[logger]
level = "info"

[client]
toolbarMode = "viewer"